apiVersion: v1
kind: Secret
metadata:
  name: istiod-lite-hack
stringData:
  istiod-lite-hack.yaml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name":"istiod"}})
    #@overlay/match-child-defaults missing_ok=True
    ---
    spec:
      replicas: 1
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: discovery
            resources:
              requests:
                cpu: 500m
                memory: 1024Mi
